import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

function readFrontendSource(relativePath: string) {
  return readFileSync(resolve(process.cwd(), relativePath), 'utf8')
}

const forbiddenLooseTypePattern = new RegExp(`\\b${'an'}${'y'}\\b|as ${'an'}${'y'}|Record<string, ${'an'}${'y'}>`)

describe('AI image playground contract', () => {
  it('uses task-owned file metadata instead of global image asset endpoints', () => {
    const source = readFrontendSource('src/api/ai/images.ts')

    expect(source).toContain("import request from '@/lib/http'")
    expect(source).toContain('request.get<AiImageInitResponse>(`${BASE}/page-init`)')
    expect(source).toContain('request.get<PaginatedResponse<AiImageTaskItem>>(BASE')
    expect(source).toContain('request.get<AiImageDetailResponse>(`${BASE}/${positiveID(params.id')
    expect(source).toContain('request.post<AiImageCreateTaskResponse, AiImageTaskCreatePayload>(BASE')
    expect(source).toContain('request.delete<void>(`${BASE}/${id}`)')
    expect(source).toContain('export interface AiImageFileInput')
    expect(source).toContain('export type AiImageMaskFileInput')
    expect(source).toContain('input_files?: AiImageFileInput[]')
    expect(source).toContain('mask_file?: AiImageMaskFileInput | null')
    expect(source).toContain('related_sort_order: number')
    expect(source).not.toContain('request.post<AiImageAssetItem, AiImageAssetCreatePayload>(`${BASE}/assets`')
    expect(source).not.toContain('AiImageAssetCreatePayload')
    expect(source).not.toContain('createAsset')
    expect(source).not.toContain('addAsset')
    expect(source).not.toContain('input_asset_ids')
    expect(source).not.toContain('mask_asset_id')
    expect(source).not.toContain('provider_id?:')
    expect(source).not.toContain('/favorite')
    expect(source).not.toContain('is_favorite')
    expect(source).not.toContain('api_key')
    expect(source).not.toContain('indexedDB')
    expect(source).not.toContain('localStorage')
    expect(source).not.toMatch(forbiddenLooseTypePattern)
  })

  it('keeps the route view thin and splits real image UI components', () => {
    const page = readFrontendSource('src/views/Main/ai/image-playground/index.vue')
    const composer = readFrontendSource('src/views/Main/ai/image-playground/components/ImageComposer/index.vue')
    const assets = readFrontendSource('src/views/Main/ai/image-playground/components/ImageAssetList/index.vue')
    const history = readFrontendSource('src/views/Main/ai/image-playground/components/ImageHistoryGrid/index.vue')
    const result = readFrontendSource('src/views/Main/ai/image-playground/components/ImageResultPanel/index.vue')
    const mask = readFrontendSource('src/views/Main/ai/image-playground/components/ImageMaskDialog/index.vue')
    const combined = `${page}\n${composer}\n${assets}\n${history}\n${result}\n${mask}`

    expect(page).toContain('<ImageComposer')
    expect(page).toContain('<ImageHistoryGrid')
    expect(page).toContain('<ImageResultPanel')
    expect(page).toContain('<ImageMaskDialog')
    expect(page).not.toContain('<ImageTaskDetailDialog')
    expect(page).toContain('AiImageApi.pageInit')
    expect(page).toContain('AiImageApi.createTask')
    expect(page).toContain("folderName: 'ai-images'")
    expect(page).toContain("userStore.can('ai_image_task_add')")
    expect(page).toContain('toImageFileInput')
    expect(page).not.toContain('AiImageApi.createAsset')
    expect(composer).toContain('defineModel<ImageComposerState>')
    expect(composer).toContain("emit('uploadFile'")
    expect(history).toContain('deleteSelected')
    expect(result).toContain("emit('retry'")
    expect(result).toContain("emit('saveAsset'")
    expect(result).toContain("emit('addReference'")
    expect(result).toContain("import type { AiImageDetailResponse, AiImageFileItem, AiImageTaskStatus } from '@/api/ai/images'")
    expect(result).toContain(':type="statusType(resultState)"')
    expect(mask).toContain("source_type: 'mask'")
    expect(combined).not.toContain('AiImageAssetItem')
    expect(combined).not.toContain('input_asset_ids')
    expect(combined).not.toContain('mask_asset_id')
    expect(combined).not.toContain('mask_target_asset_id')
    expect(combined).not.toContain('provider_id?:')
    expect(combined).not.toContain('api_key')
    expect(combined).not.toContain('indexedDB')
    expect(combined).not.toContain('localStorage')
    expect(combined).not.toMatch(forbiddenLooseTypePattern)
  })

  it('keeps the image playground inside the outer layout card instead of nesting overflow-prone cards', () => {
    const page = readFrontendSource('src/views/Main/ai/image-playground/index.vue')
    const composer = readFrontendSource('src/views/Main/ai/image-playground/components/ImageComposer/index.vue')
    const history = readFrontendSource('src/views/Main/ai/image-playground/components/ImageHistoryGrid/index.vue')
    const result = readFrontendSource('src/views/Main/ai/image-playground/components/ImageResultPanel/index.vue')

    expect(page).toContain('image-workspace--three-panel')
    expect(page).toContain('class="image-panel image-panel--records"')
    expect(page).toContain('class="image-panel image-panel--composer"')
    expect(page).toContain('class="image-panel image-panel--result"')
    expect(page).toContain('overflow: hidden;')
    expect(page).toContain('min-width: 0;')
    expect(composer).not.toContain('<el-card')
    expect(history).not.toContain('<el-card')
    expect(result).not.toContain('<el-card')
  })

  it('renders image task details inline in the right result panel instead of a dialog', () => {
    const page = readFrontendSource('src/views/Main/ai/image-playground/index.vue')
    const result = readFrontendSource('src/views/Main/ai/image-playground/components/ImageResultPanel/index.vue')

    expect(page).toContain('<ImageResultPanel')
    expect(page).not.toContain('detailVisible')
    expect(page).not.toContain('ImageTaskDetailDialog')
    expect(result).toContain('class="result-panel"')
    expect(result).toContain('class="result-stage"')
    expect(result).not.toContain('<AppDialog')
    expect(result).not.toContain('<el-dialog')
  })

  it('exposes only task wrappers after deleting global asset registration', () => {
    const source = readFrontendSource('src/api/ai/images.ts')
    const page = readFrontendSource('src/views/Main/ai/image-playground/index.vue')

    expect(source).toContain('const pageInit = () => request.get<AiImageInitResponse>')
    expect(source).toContain('const createTask = (payload: AiImageTaskCreatePayload)')
    expect(source).toContain('const deleteOne = (params: { id: Id })')
    expect(source).toContain('const deleteBatch = async (params: { ids: Id[] })')
    expect(source).toContain('pageInit,')
    expect(source).toContain('createTask,')
    expect(source).toContain('deleteOne,')
    expect(source).toContain('deleteBatch,')
    expect(source).toContain('addTask: createTask')
    expect(source).not.toContain('const createAsset')
    expect(source).not.toContain('createAsset,')
    expect(source).not.toContain('addAsset:')
    expect(page).toContain('AiImageApi.pageInit()')
    expect(page).toContain('AiImageApi.createTask')
    expect(page).not.toContain('AiImageApi.createAsset')
    expect(page).not.toContain('AiImageApi.init')
    expect(page).not.toContain('AiImageApi.addAsset')
    expect(page).not.toContain('AiImageApi.addTask')
  })

  it('normalizes optional create-task payload fields without logical-or fallbacks', () => {
    const source = readFrontendSource('src/api/ai/images.ts')

    expect(source).not.toContain('payload.size || undefined')
    expect(source).not.toContain('payload.quality || undefined')
    expect(source).not.toContain('payload.output_format || undefined')
    expect(source).not.toContain('payload.output_compression')
    expect(source).not.toContain('payload.moderation || undefined')
    expect(source).not.toContain('payload.input_asset_ids')
    expect(source).not.toContain('payload.mask_asset_id')
    expect(source).not.toContain('payload.mask_target_asset_id')

    expect(source).toContain('function optionalImageEnum')
    expect(source).toContain('size: optionalImageEnum(payload.size),')
    expect(source).toContain('input_files: payload.input_files,')
    expect(source).toContain('mask_file: payload.mask_file,')
  })
})
